spring:
  redis:
    db1:
      host: localhost
      port: 6379
      password: 123456
      database: 0
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
        max-idle: 8
      timeout: 0
    db2:
      host: localhost
      port: 6379
      password: 123456
      database: 2
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
        max-idle: 8
      timeout: 0
  application:
    name: multi-resource
  data:
    mongodb:
      db1:
        host: localhost
        port: 27017
        database: db1

      db2:
        host: localhost
        port: 27017
        database: db2
  datasource:
    mysql1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: 123456
    mysql2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: 123456
  aop:
    auto: true
    proxy-target-class: true

server:
  port: 8080

